### PR TITLE
Milestone 3: friendship-v2

### PR DESCRIPTION
**Pull request by enaburekhan**
**Milestone 3: Friendship-v2**
**In this project:**

- Add integration test for sign-in, sign-out, and friendship
- Add negative test scenarios
- Add button to add and remove friends
- Add user controller test
- Add post controller test
- A signed-in user should not be able to see another user's post in the timeline until that user accepts the friend request. This is working perfectly
- When a signed-in user goes to the profile of another user who is not a friend, he should not be able to view their post. This is also working perfectly.

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @enaburekhan and @Ceejayski :clap: :clap:
#### Kudos :+1:  to you for a job well done. The project looks great and well implemented aside from a few issues. Check my comments below :point_down:

#### Pull Request:
- _The Pull Request does not look professional: it only contains one commit and did not include a descriptive summary(please include a summary of what you did in the Pull Request)_

#### Controller:
- _PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)). Currently, it also contains `@post = Post.new` which I think should be in separate action method `new`_

#### [Optional] Tests:
- _Add integration tests that cover: sign in, sign up, friend request_
- _Add tests that cover: user controller, friendship controller_

#### _Reviewed by Temitayo Adeleke_

**Comment by enaburekhan** [comment]
**Code review changes effected**

- Add integration test for sign-up and sign-in 
- Add user controller test
- Add friendship test

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:
### Hi @enaburekhan and @Ceejayski  ! 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] Your project looks great. However, your project cannot be approved until you write a descriptive PR Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.
- [ ] Add negative case scenarios to your test files.
- [ ] Fix the errors in your test files.
- [ ] A signed-in user should not be able to see another user's post in the timeline until that user accepts the friend request.
- [ ] When a signed-in user goes to the profile of another user who is not a friend, he should not be able to view their post.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Congratulations on successfully completing this milestone. You implemented the changes required by the previous TSE. You can go ahead and merge this PR. 👍 

Goodluck on your next project and Happy Coding 💻

**Pull request merged**
